language: java
os: linux
jdk: openjdk8
git:
  depth: false # https://stackoverflow.com/a/51727114/3714539
before_install:
  - source scripts/setup-cli-tools.sh
script: scripts/travis.sh
addons:
  apt:
    update: true
stages:
  - name: test
    if: (branch = master AND type = push) AND (tag IS NOT present)
  - name: release-snapshot
    if: (branch = master AND type = push) AND (tag IS NOT present)
  - name: release
    if: tag IS present
  - name: upload-jar-launchers
  - name: upload-native-launchers
  - name: update-brew-formula
  - name: update-website
jobs:
  include:
    - env: SCALA_VERSION=2.12 BOOTSTRAP=1
      addons:
        apt:
          packages:
            - nailgun
    - env: SCALA_VERSION=2.13
      sudo: required
      services: docker
    - env: SCALA_VERSION=2.12
      sudo: required
      services: docker
      before_script: source scripts/travis-setup-graalvm.sh
    - env: SCALA_VERSION=2.12
      jdk: openjdk11
      script: sbt scala212 test:compile testsJVM/test
    - env: SCALA_VERSION=2.12 NATIVE=1
      before_script: curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
    - env: SCALA_VERSION=2.12 SCALA_JS=1
    - name: "Website"
      script: amm website.sc generate
    # - name: "Pants"
    # - before_script: pyenv global system 3.6.7
    # - # Sanity check for Pants build path.
    # - script: cd modules && ./pants run cli:coursier-cli -- fetch --help
    - stage: release-snapshot
      env: DUMMY_PROGUARD=1
      script: sbt ci-release
    - stage: release
      # publishLocal so that proguard and all compilation run before any publishing
      script: sbt +publishLocal ci-release
    - stage: upload-jar-launchers
      env: TRAVIS_TAG=v2.0.0-RC5-5
      script: amm launcher.sc uploadAllJars
    - stage: upload-jar-launchers
      env: TRAVIS_TAG=v2.0.0-RC5-5
      name: "Push Linux graalvm launcher"
      before_script: source scripts/travis-setup-graalvm.sh
      script: amm launcher.sc uploadNativeImage
    - stage: upload-jar-launchers
      env: TRAVIS_TAG=v2.0.0-RC5-5
      name: "Push OS X graalvm launcher"
      os: osx
      osx_image: xcode9.4
      jdk: openjdk9
      before_script: source scripts/travis-setup-graalvm.sh
      script: amm launcher.sc uploadNativeImage
    - stage: upload-jar-launchers
      env: TRAVIS_TAG=v2.0.0-RC5-5
      name: "Push Windows graalvm launcher"
      os: windows
      language: bash
      before_script: source scripts/travis-setup-graalvm.sh
      script: echo "$PATH" && (which bash || true) && scripts/windows-native-image.bat
    - stage: update-brew-formula
      env: TRAVIS_TAG=v2.0.0-RC5-4
      script: scripts/update-brew-formula.sh
    - stage: update-website
      env: TRAVIS_TAG=v2.0.0-RC5-5
      name: "Push website"
      script:
        - npm install
        - export PATH="$PATH:$(pwd)/node_modules/bower/bin"
        - amm website.sc updateWebsite
branches:
  only:
  - rework-ci-graalvm-19.3
  - /^v\d+\.\d+.*$/ # tagged versions
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.cache
  - $HOME/.jabba/jdk
